Controllers/ProductandCategoryController.cs
using MVCMachineTask.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;


namespace MVCMachineTask.Controllers
{
    public class ProductandCategoryController : Controller
    {
        public ActionResult Index(string Search, int? page)
        {
            List<ProductandCategory> productandcategorylist = new List<ProductandCategory>();
            string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["MVCMachineTaskconnection"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(connectionString);
            SqlCommand cmd = new SqlCommand("SPJOINPRODUCTANDCATEGORY", sqlConnection);
            sqlConnection.Open();
            cmd.CommandType = CommandType.StoredProcedure;
            SqlDataReader sqlDataReader = cmd.ExecuteReader();
            while (sqlDataReader.Read())
            {
                ProductandCategory product = new ProductandCategory();
                product.ProductId = Convert.ToInt32(sqlDataReader["ProductId"]);
                product.ProductName = Convert.ToString(sqlDataReader["ProductName"]);
                product.CategoryId = Convert.ToInt32(sqlDataReader["CategoryId"]);
                product.CategoryName = Convert.ToString(sqlDataReader["CategoryName"]);
                productandcategorylist.Add(product);
            }
            sqlDataReader.Close();
            sqlConnection.Close();
            var data = productandcategorylist.ToPagedList(page ?? 1, 10);
            return View(data);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top bg-info">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVCMachineTask", "Index", "ProductandCategory", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Product", "Index", "Product")</li>
                    <li>@Html.ActionLink("Category", "Index", "Category")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>